In [1]:
import numpy as np

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2 = a[np.newaxis, :]

In [4]:
a2.shape

(1, 10)

In [8]:
print(a[0])

0


In [9]:
np.arange(2, 5, 2)

array([2, 4])

In [2]:
B = np.random.rand(100000000)
%timeit sum(B)

9.84 s ± 632 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit np.sum(B)

129 ms ± 857 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%%timeit
S=0
for x in B:
    S+=x

14.5 s ± 220 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
#1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age
age=np.random.randint(10,22,size=(7,4))
age

array([[10, 13, 19, 18],
       [19, 12, 18, 10],
       [10, 13, 10, 14],
       [13, 12, 11, 14],
       [16, 14, 18, 14],
       [14, 14, 17, 13],
       [19, 16, 19, 21]])

In [6]:
print("age",age.size)

age 28


In [7]:
#2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array
x=np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
#3. Create an equally spaced numpy array with 27 elements between 4 and 7
import numpy as np
s=np.linspace(4,7,27)
s

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

In [9]:
print("length:",len(s))

length: 27


In [10]:
#4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.
m=np.round(np.random.rand(5,4),2)
m

array([[0.16, 0.08, 0.47, 0.64],
       [0.69, 0.08, 0.38, 0.05],
       [0.59, 0.15, 0.39, 0.09],
       [0.51, 0.67, 0.41, 0.4 ],
       [0.63, 0.61, 0.01, 0.08]])

In [11]:
#5. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.
m1=np.random.randint(5,15,size=(5,5))
m1

array([[14, 10, 10, 13, 14],
       [ 6,  6,  8, 13,  8],
       [ 9, 13, 11,  6,  5],
       [ 9,  8,  8,  5, 11],
       [11,  9,  7,  5,  9]])

In [12]:
#6. Create the one dimensional array of zeros of random length below 20 with the data type int32
#import numpy as np
m2=np.zeros(np.random.randint(1,20),dtype='int32')
m2

array([0, 0, 0, 0, 0, 0, 0])

In [13]:
#7. Create a two dimensional array of ones of random row and column lengths with the data type of float32
import numpy as np
arr=np.arange(20,dtype='float32').reshape(4,5)
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)

In [14]:
sol1=np.ones((np.random.randint(1,20),np.random.randint(1,20)),dtype='float32')
sol1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [15]:
#8. Create a matrix exactly as same as shown below and print its shape, type and dtype
arr1=np.array([ [9,25,50,34,45],
                [3,34,34,65,2],
                [5,7,3,76,3],
                [7,8,6,54,6],
                [23,12,8,5,8]])
print(np.shape(arr1))
print(arr1.ndim)
print(arr1.dtype)
print(arr1)

(5, 5)
2
int32
[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]


In [16]:
arr1=np.array([ [9,25,50,34,45],
                [3,34,34,65,2],
                [5,7,3,76,3],
                [7,8,6,54,6],
                [23,12,8,5,8]])
arr1[:3,::3]


array([[ 9, 34],
       [ 3, 65],
       [ 5, 76]])

In [16]:
#9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)
print("Centre element is: ",arr1[2,2])

Centre element is:  3


In [17]:
#10. Print the all the elements of 3rd row of the matrix
print(arr1[2])

[ 5  7  3 76  3]


In [18]:
#11. Print the all the elements of 4th columns of the matrix
print(arr1[:,3])

[34 65 76 54  5]


In [19]:
#12. Print the 4 corner pixels of the matrix
x1=arr1[[0,4],:]
y1=x1[:,[0,4]]
y1

array([[ 9, 45],
       [23,  8]])

In [20]:
#13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
import numpy as np
m1=arr1[0:2,2:4]
m3=arr1[2:5,2:5]
m2=arr1[3:5,0:2]
print(m1)
print(m2)
print(m3)

[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


In [21]:
#14. Reshape all the three matrix segmented in the above task in to three 1-dimensional vector.

n1=m1.reshape((1,4))
print(n1)
n2=m2.reshape((1,4))
print(n2)
n3=m3.reshape((1,9))
print(n3)

[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


In [22]:
#15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction
import numpy as np
print('Row wise: \n',np.concatenate((m1,m2)))
print('Column wise: \n',np.concatenate((m1,m2),axis=1))

Row wise: 
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
Column wise: 
 [[50 34  7  8]
 [34 65 23 12]]


In [23]:
#16. Add, Subtract, multiply, divide the matrixes m1 and m2
add=m1+m2
mul=m1*m2
sub=m1-m2
div=m1/m2
print(add)
print(mul)
print(sub)
print(div)

[[57 42]
 [57 77]]
[[350 272]
 [782 780]]
[[43 26]
 [11 53]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


In [24]:
#17. Add the m1 with m3 by removing the first row and last column of m3
print(m1,m3,sep='\n')
new_m=m3[1:,:-1]
new_m+m1

[[50 34]
 [34 65]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


array([[56, 88],
       [42, 70]])

In [25]:
#18.  Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.
new_m1=np.mean(m1[:,0])
new_m2=np.mean(m1[:,1])
print(new_m1,new_m2)
new__m3=np.hstack([new_m1,new_m2])
print(new__m3)
new_var=np.mean(m1,axis=0)
print(new_var)
m4=np.vstack([m1,new_var])
m4

42.0 49.5
[42.  49.5]
[42.  49.5]


array([[50. , 34. ],
       [34. , 65. ],
       [42. , 49.5]])

In [26]:
#19. Perform the matrix multiplication between m3 and m4
m5=np.dot(m3,m4)
m5

array([[2860. , 5190.5],
       [2388. , 4011. ],
       [ 906. ,  993. ]])

In [27]:
#20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.
print(min(np.mean(arr1, axis=0)))
print(max(np.max(arr1,axis=1)))
print(min(np.var(arr1,axis=0)))
print(max(np.var(arr1,axis=1)))
print(min(np.std(arr1,axis=0)))
print(max(np.std(arr1,axis=1)))

9.4
76
50.239999999999995
820.1600000000001
7.08801805866774
28.63843571147


In [28]:
#//min=np.mean(arr1,axis=1)#min

In [29]:
#21.  Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
balls=np.array([['MSD',50,42,22,78],['Kholi',95,8,65,43],['Rohit',9,100,7,101],['Rahul',27,3,11,31],['Dhawan',24,20,36,27]])
run=np.array([['MSD',54,60,10,65],['Kholi',102,2,78,32],['Rohit',3,110,1,92],['Rahul',56,6,12,42],['Dhawan',12,8,22,11]])
print(balls)
ball=balls[:,1:5]
print('\n the ball matrix \n',ball)
ball1=ball.astype("int32")
runs=run[:,1:5]
print('\n the run matrix \n',run)
run1=runs.astype("int32")
strike=run1/ball1 *100
print(strike)
sr=strike.mean(axis=1)
print("\n the strike for each player :\n ",sr)
sr1=sr.reshape([5,1])
sr1
player_sr=np.concatenate([balls,sr1],axis=1)
print("\n player ball faced with strike run rate: \n",player_sr)
ind=sr.argsort()   #ascending
ind
final_output=player_sr[ind,:][::-1]
print("\n final list: \n",final_output)

[['MSD' '50' '42' '22' '78']
 ['Kholi' '95' '8' '65' '43']
 ['Rohit' '9' '100' '7' '101']
 ['Rahul' '27' '3' '11' '31']
 ['Dhawan' '24' '20' '36' '27']]

 the ball matrix 
 [['50' '42' '22' '78']
 ['95' '8' '65' '43']
 ['9' '100' '7' '101']
 ['27' '3' '11' '31']
 ['24' '20' '36' '27']]

 the run matrix 
 [['MSD' '54' '60' '10' '65']
 ['Kholi' '102' '2' '78' '32']
 ['Rohit' '3' '110' '1' '92']
 ['Rahul' '56' '6' '12' '42']
 ['Dhawan' '12' '8' '22' '11']]
[[108.         142.85714286  45.45454545  83.33333333]
 [107.36842105  25.         120.          74.41860465]
 [ 33.33333333 110.          14.28571429  91.08910891]
 [207.40740741 200.         109.09090909 135.48387097]
 [ 50.          40.          61.11111111  40.74074074]]

 the strike for each player :
  [ 94.91125541  81.69675643  62.17703913 162.99554687  47.96296296]

 player ball faced with strike run rate: 
 [['MSD' '50' '42' '22' '78' '94.91125541125541']
 ['Kholi' '95' '8' '65' '43' '81.69675642594859']
 ['Rohit' '9' '100' '7'

In [30]:
#22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]). Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed.
marks = np.array([65,84,47,56,89,98,48,77,80,39])
pass_ind=np.where(marks>50)
a=marks[marks>50]
pass_marks=marks[pass_ind]
fail_ind=np.where(marks<50)
fail_marks=marks[fail_ind]
print('student passed : ',len(pass_marks))
print('student failed : ',fail_marks)

student passed :  7
student failed :  [47 48 39]


In [31]:
#alt...
marks = np.array([65,84,47,56,89,98,48,77,80,39])
a=marks[marks<50]
print('student passed : ',(marks.size)-(a.size))
print('student failed : ',a.size)

student passed :  7
student failed :  3


In [32]:
#23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.
new_marks=marks.copy()
new_marks
mercy_marks=np.where((new_marks>45) & (new_marks<=49))
new_marks[mercy_marks]=new_marks[mercy_marks]+5
bonus_marks=np.where((new_marks>80) & (new_marks<=95))
new_marks[bonus_marks]=new_marks[bonus_marks]+5

new_marks1=np.where(new_marks>95)
new_marks[bonus_marks]=100

print('\n Actual Student marks \n', marks)
print('\n New marks which provides to student marks \n',new_marks)
actual_pass_marks=(len(marks[np.where(marks>=50)])/len(marks))*100
our_new_marks=(len(new_marks[np.where(new_marks>=50)])/len(new_marks))*100
inc_in_percentage=our_new_marks-actual_pass_marks
print("\n percentage increase in marks \n",inc_in_percentage)


 Actual Student marks 
 [65 84 47 56 89 98 48 77 80 39]

 New marks which provides to student marks 
 [ 65 100  52  56 100  98  53  77  80  39]

 percentage increase in marks 
 20.0


In [33]:
#24.  Print the time taken for performing the following operation using list and numpy array
#(x(i)^2 +8) / y(i), where x and y are real integers from 1 to 60000
import time
x=range(1,60000)
y=range(1,60000)
out=[]
st=time.time()
for i,j in zip(x,y):
    out.append((x[i-1]*x[i-1]+8)/y[i-1])
print('time taken to complete the computing using list : ', (time.time()-st)*1000)

x_arr=np.arange(1,60000)
y_arr=np.arange(1,60000)
st_t=time.time()
out_arr=((x_arr*x_arr)+8)/y_arr
print('time taken to comlete to computing sing numpy : ',(time.time()-st_t)*1000)

time taken to complete the computing using list :  63.992977142333984
time taken to comlete to computing sing numpy :  0.0


In [34]:
#get dates of yesterday,today and tomorrow
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterda",yesterday)
today=np.datetime64('today','D')
print("Today,today")
tmrrw=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow",tmrrw)

Yesterda 2021-09-18
Today,today
Tomorrow 2021-09-20


In [35]:
#display all dates of any particular month
print("September,2021")
print(np.arange('2021-09','2021-10',dtype='datetime64[D]'))

September,2021
['2021-09-01' '2021-09-02' '2021-09-03' '2021-09-04' '2021-09-05'
 '2021-09-06' '2021-09-07' '2021-09-08' '2021-09-09' '2021-09-10'
 '2021-09-11' '2021-09-12' '2021-09-13' '2021-09-14' '2021-09-15'
 '2021-09-16' '2021-09-17' '2021-09-18' '2021-09-19' '2021-09-20'
 '2021-09-21' '2021-09-22' '2021-09-23' '2021-09-24' '2021-09-25'
 '2021-09-26' '2021-09-27' '2021-09-28' '2021-09-29' '2021-09-30']


In [36]:
#wap to get dates of yesterday,today,tomorrow
print("Number of days, February, 2022: ")
print(np.datetime64('2022-03-01') - np.datetime64('2022-02-01'))
print("Number of days, February, 2021: ")
print(np.datetime64('2021-03-01') - np.datetime64('2021-02-01'))
print("Number of days, February, 2020: ")
print(np.datetime64('2020-03-01') - np.datetime64('2020-02-01'))

Number of days, February, 2022: 
28 days
Number of days, February, 2021: 
28 days
Number of days, February, 2020: 
29 days


In [37]:
#sorting and searching of a given complex array using numpy 
complex_num=[1+1j,2+5j,1-2j]
print("Original Array:\n ",complex_num)
print("Sorted the complex array using real in first part and impaginary part in second:",np.sort_complex(complex_num))

Original Array:
  [(1+1j), (2+5j), (1-2j)]
Sorted the complex array using real in first part and impaginary part in second: [1.-2.j 1.+1.j 2.+5.j]


In [38]:
#getting indices of the sorted elements
i=np.argsort(complex_num)
print("Indices are: ",i)

Indices are:  [2 0 1]
